// Generated by CoffeeScript 1.6.3
module.exports = function(options) {
  var data, k, meta, script, scripts, stylesheet, stylesheets, v;
  scripts = (function() {
    var _i, _len, _ref, _results;
    _ref = options.scripts || [];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      script = _ref[_i];
      _results.push("<script src='" + script + "'></script>");
    }
    return _results;
  })();
  stylesheets = (function() {
    var _i, _len, _ref, _results;
    _ref = options.stylesheets || [];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      stylesheet = _ref[_i];
      _results.push("<link rel='stylesheet' href='" + stylesheet + "'>");
    }
    return _results;
  })();
  meta = (function() {
    var _ref, _results;
    _ref = options.meta || {};
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      _results.push("<meta name='" + k + "' content='" + v + "' />");
    }
    return _results;
  })();
  data = "<!doctype>\n<title>" + (options.title || 'page') + "</title>\n" + (meta.join('\n')) + "\n" + (stylesheets.join('\n')) + "\n" + (scripts.join('\n'));
  if (options.data) {
    data += "<script>\n  var " + (options.dataKey || '__data') + " = " + (JSON.stringify(options.data)) + ";\n</script>";
  }
  return function(req, res) {
    return res.send(data);
  };
};
